### PR TITLE
update first test pls

### PR DESCRIPTION
**Pull request by StrixLuca**
pls first test the branch pls

### CODE REVIEW

**Review by drazoxXD — APPROVED** [review]

**Comment by StrixLuca** [comment]
[drazoxXD] First test the branch

**Review by drazoxXD — CHANGES_REQUESTED** [review]
Cant spawn
Timer has error
https://cdn.discordapp.com/attachments/1161707843041378454/1162144363468574800/image.png?ex=653ade47&is=65286947&hm=9987ceaea53871b5b48694dec2fedaa9ef4985a02e2c30f9ce1dc5f6ac316b43&

**Comment by drazoxXD** [comment]
Can't open weapon shop after spawn!

Fiaxable with a script restart but still needs a fix!

**Comment by StrixLuca** [comment]
> Can't open weapon shop after spawn!
> 
> Fiaxable with a script restart but still needs a fix!

and now?

**Comment by StrixLuca** [comment]
test all the scripts i have change

**Comment by drazoxXD** [comment]
Everything is good!

**Comment by StrixLuca** [comment]
> Everything is good!

can i join the server to for testing

**Comment by StrixLuca** [comment]
I'm afraid that something won't work because of me ahah

**Pull request merged**
